"""Added tickets and shows

Revision ID: 189b629c65be
Revises: 9c7b82b2c00d
Create Date: 2020-02-29 22:06:35.350042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189b629c65be'
down_revision = '9c7b82b2c00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_status')
    # ### end Alembic commands ###
