"""Added registered_on and public_id columns

Revision ID: 30b277c64759
Revises: 99e508d97212
Create Date: 2020-02-29 20:03:19.450017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b277c64759'
down_revision = '99e508d97212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'user', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###
