"""Added ticket status

Revision ID: 6754c183398b
Revises: 189b629c65be
Create Date: 2020-02-29 22:07:21.034913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6754c183398b'
down_revision = '189b629c65be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('ticket_status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'ticket_status', ['ticket_status'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'ticket_status')
    # ### end Alembic commands ###
