"""Added foreign keys to movie table

Revision ID: 89941f1bc794
Revises: 160f432b82f9
Create Date: 2020-02-29 21:30:17.601861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89941f1bc794'
down_revision = '160f432b82f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('certificate_id', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('language_id', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('view_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movie', 'certificate', ['certificate_id'], ['id'])
    op.create_foreign_key(None, 'movie', 'view', ['view_id'], ['id'])
    op.create_foreign_key(None, 'movie', 'genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'movie', 'language', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_column('movie', 'view_id')
    op.drop_column('movie', 'language_id')
    op.drop_column('movie', 'genre_id')
    op.drop_column('movie', 'certificate_id')
    # ### end Alembic commands ###
