"""Added screen layout

Revision ID: b537a770a04e
Revises: dc6cba5589b4
Create Date: 2020-02-29 21:52:55.997098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b537a770a04e'
down_revision = 'dc6cba5589b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=True),
    sa.Column('row', sa.String(length=10), nullable=False),
    sa.Column('seat', sa.String(length=10), nullable=False),
    sa.Column('x_cordinate', sa.Integer(), nullable=False),
    sa.Column('y_cordinates', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layout')
    # ### end Alembic commands ###
