"""Added screen and foreign keys

Revision ID: dc6cba5589b4
Revises: 23aaa7161eea
Create Date: 2020-02-29 21:47:00.058344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6cba5589b4'
down_revision = '23aaa7161eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cinema', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cinema', 'city', ['city_id'], ['id'])
    op.add_column('city', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'city', 'state', ['state_id'], ['id'])
    op.add_column('state', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'state', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'state', type_='foreignkey')
    op.drop_column('state', 'country_id')
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.drop_column('city', 'state_id')
    op.drop_constraint(None, 'cinema', type_='foreignkey')
    op.drop_column('cinema', 'city_id')
    op.drop_table('screen')
    # ### end Alembic commands ###
