"""Unique

Revision ID: e121f4497519
Revises: b723324684ce
Create Date: 2020-02-29 22:37:02.362948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e121f4497519'
down_revision = 'b723324684ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'certificate', ['name'])
    op.create_unique_constraint(None, 'city', ['name'])
    op.create_unique_constraint(None, 'country', ['name'])
    op.create_unique_constraint(None, 'genre', ['name'])
    op.create_unique_constraint(None, 'language', ['name'])
    op.create_unique_constraint(None, 'state', ['name'])
    op.create_unique_constraint(None, 'view', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'view', type_='unique')
    op.drop_constraint(None, 'state', type_='unique')
    op.drop_constraint(None, 'language', type_='unique')
    op.drop_constraint(None, 'genre', type_='unique')
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_constraint(None, 'certificate', type_='unique')
    # ### end Alembic commands ###
